# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: july25export.c8zxpiwl6bkl.eu-central-1.rds.amazonaws.com
  port: 5432
  database: my_remote_db
  username: olivdbusr
  password: postgres

development:
  <<: *default
  database: olivdb
test:
  <<: *default
  database: olivdb

production:
  <<: *default
  database: olivdb
  username: blogs
  password: <%= ENV["BLOGS_DATABASE_PASSWORD"] %>
